---
- hosts: challenges
  gather_facts: False
  tasks:
  - name: install python 2
    become: true
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: challenges
  vars_files:
    - roles/narwhal/vars/config.yml
  roles:
    - role: antoiner77.caddy
      become: true
      caddy_setcap: yes
      caddy_systemd_capabilities_enabled: true
      caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
      caddy_config: |
        {{ narwhal_url }} {
          proxy / localhost:8000 {
            transparent
          }
        }
        {{ challenge_wildcard_url }} {
          proxy / localhost:8001 {
            transparent
          }
        }
    - narwhal
