---
- hosts: shell
  gather_facts: False
  tasks:
  - name: install python 2
    become: true
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: shell
  become: true
  roles:
    - shell

- hosts: shell
  roles:
    - role: caddy_ansible.caddy_ansible
      vars_files:
        - roles/shell/vars/config.yml
      become: true
      caddy_setcap: yes
      caddy_systemd_capabilities_enabled: true
      caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
      caddy_config: |
        {{ shell_deploy_url }} {
          proxy / localhost:8000 {
            transparent
          }
        }
        {{ web_shell_url }} {
          root /srv/webshell
        }
        {{ websocket_proxy_url }} {
          proxy / http://localhost:5999 {
            websocket
          }
          tls {
            alpn http/1.1
          }
        }